### ISSUE TITLE
streamlit deployment

### ISSUE THREAD

**Issue by SteinsGate9** [CMU-IDS-2021/fp--05839-jpark-etatum-shuang#1]
Hello TAs,
Could you help us deploy this project to streamlit like you did in assignment2? 
requirement.txt is in the repo and we could run this project with 'streamlit run main.py'
Thanks a lot !

**Comment by kunalkhadilkar** [comment]
https://share.streamlit.io/cmu-ids-2021/fp--05839-jpark-etatum-shuang/main/main.py
